version: '3.8'
services:
    nginx:
        image: nginx:1.16
        ports:
         - 80:80
        volumes:
         - type: bind
           source: ./configs/nginx/default.conf
           target: /etc/nginx/conf.d/default.conf
    jupyter-tensorflow:
        build: ./build/app
        image: jupyter-tensorflow
        ports:
         - 8888:8888
        volumes:
         - jupyter-notebooks:/jupyter-notebooks
    portainer: 
        image: portainer/portainer:latest
        ports:
         - 9000:9000
        volumes:
         - portainer-data:/data
         - /var/run/docker.sock:/var/run/docker.sock
        restart: always
volumes:
    jupyter-notebooks:
        driver: local
    portainer-data:
        driver: local